# Generated by Django 4.1.3 on 2022-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrazyThings", "0011_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("cr", "cricket"),
                    ("ba", "badminton"),
                    ("cy", "cycling"),
                    ("fo", "football"),
                    ("sw", "swimming"),
                    ("vb", "volleyball"),
                    ("bb", "basketball"),
                    ("tt", "tabletennis"),
                    ("m", "mobile"),
                    ("tv", "television"),
                    ("l", "laptop"),
                    ("c", "camera"),
                    ("hp", "Headphone"),
                    ("s", "speaker"),
                    ("sm", "smartwatch"),
                    ("p", "printer"),
                    ("b", "beds"),
                    ("so", "sofas"),
                    ("ch", "chairs"),
                    ("t", "tables"),
                    ("w", "wardrobes"),
                    ("sh", "shelves"),
                    ("ca", "cabinet"),
                    ("ma", "mattress"),
                    ("me", "mens"),
                    ("wo", "women"),
                    ("ki", "kids"),
                    ("s", "shoes"),
                    ("je", "jewellery"),
                    ("wa", "watches"),
                    ("ha", "handbags"),
                    ("sc", "school"),
                    ("ex", "exam"),
                    ("un", "university"),
                    ("co", "comics"),
                    ("cd", "children"),
                    ("ac", "air"),
                    ("r", "refrigerator"),
                    ("w", "washing"),
                    ("co", "cooler"),
                    ("f", "fan"),
                    ("v", "vitamins"),
                    ("p", "personal"),
                    ("fv", "fruitvegetable"),
                    ("be", "beverages"),
                    ("fg", "foodgrains"),
                    ("co", "cookies"),
                    ("no", "noodles"),
                    ("ol", "oil"),
                    ("sn", "snacks"),
                    ("de", "deo"),
                ],
                max_length=5,
            ),
        ),
    ]
